INSERT INTO comments(book_id, text)
VALUES ((SELECT id FROM books WHERE title = 'The Oblong Box'),
        'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.'),
       ((SELECT id FROM books WHERE title = 'The Oblong Box'),
        'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.'),
       ((SELECT id FROM books WHERE title = 'The Oblong Box'),
        'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.'),
       ((SELECT id FROM books WHERE title = 'Skin Deep'),
        'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh'),
       ((SELECT id FROM books WHERE title = 'Summer Catch'),
        'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis'),
       ((SELECT id FROM books WHERE title = 'Summer Catch'),
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.'),
       ((SELECT id FROM books WHERE title = 'Summer Catch'),
        'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.'),
       ((SELECT id FROM books WHERE title = 'The Missionaries'),
        'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.'),
       ((SELECT id FROM books WHERE title = 'The Missionaries'),
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae'),
       ((SELECT id FROM books WHERE title = '9 Star Hotel (Malon 9 Kochavim)'),
        'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.'),
       ((SELECT id FROM books WHERE title = '9 Star Hotel (Malon 9 Kochavim)'),
        'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.'),
       ((SELECT id FROM books WHERE title = 'Street Kings'),
        'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae'),
       ((SELECT id FROM books WHERE title = 'Street Kings'),
        'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.'),
       ((SELECT id FROM books WHERE title = 'Squeeze'),
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.'),
       ((SELECT id FROM books WHERE title = 'Squeeze'),
        'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.'),
       ((SELECT id FROM books WHERE title = 'Old San Francisco'),
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'),
       ((SELECT id FROM books WHERE title = 'Old San Francisco'),
        'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.'),
       ((SELECT id FROM books WHERE title = 'Pauly Shore Is Dead'),
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.'),
       ((SELECT id FROM books WHERE title = 'Pauly Shore Is Dead'),
        'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.'),
       ((SELECT id FROM books WHERE title = 'Wayward Bus'),
        'sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'),
       ((SELECT id FROM books WHERE title = 'Wayward Bus'),
        'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.'),
       ((SELECT id FROM books WHERE title = 'Brimstone and Treacle'),
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.'),
       ((SELECT id FROM books WHERE title = 'Brimstone and Treacle'),
        'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.'),
       ((SELECT id FROM books WHERE title = 'The Walking Stick'),
        'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.'),
       ((SELECT id FROM books WHERE title = 'The Walking Stick'),
        'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.'),
       ((SELECT id FROM books WHERE title = 'Eight Below'),
        'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.'),
       ((SELECT id FROM books WHERE title = 'Eight Below'), 'Mauris viverra diam vitae quam. Suspendisse potenti.'),
       ((SELECT id FROM books WHERE title = 'Eight Below'),
        'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;'),
       ((SELECT id FROM books WHERE title = 'Riders of the Purple Sage'),
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.'),
       ((SELECT id FROM books WHERE title = 'Harry and Tonto'),
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'),
       ((SELECT id FROM books WHERE title = 'Harry and Tonto'),
        'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.'),
       ((SELECT id FROM books WHERE title = 'Harry and Tonto'),
        'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');